const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const extract = name => html.match(new RegExp(`(?:async )?function ${name}\\([^]*?\\n\\}`))[0];
const item = {code:'TEST',qty:20,receiveDate:'2026-08-01',unit:'pcs',withdrawals:[{qty:5,date:'2026-08-02'}]};
const ctx = vm.createContext({editingSlot:{zone:'F',slot:'F-18'}, movementSaving:false,
  movementEdit:{zone:'F',slot:'F-18',itemIndex:0,type:'withdraw',index:0,snapshot:JSON.stringify(item)}});
vm.runInContext(html.match(/function escapeHtml[^\n]+/)[0],ctx);
vm.runInContext(['formatMovementDate','getRemainingQty','movementNumber','movementDateKey','getStockMovement',
  'movementMatchesSnapshot','renderMovementEditForm'].map(extract).join('\n'),ctx);
for(const invalid of ['   ',true,false,[],{},null,undefined,Infinity]) assert.equal(ctx.movementNumber(invalid),null);
assert.equal(ctx.movementNumber('0'),0);
assert.equal(ctx.movementNumber(' 2.5 '),2.5);
const reordered = {withdrawals:[{date:'2026-08-02',qty:5}],unit:'pcs',receiveDate:'2026-08-01',qty:20,code:'TEST'};
assert.equal(ctx.movementMatchesSnapshot(reordered,JSON.stringify(item)),true);
assert.equal(ctx.movementMatchesSnapshot({...item,qty:21},JSON.stringify(item)),false);
assert.equal(ctx.movementMatchesSnapshot({a:[['qty',5]]},JSON.stringify({a:{qty:5}})),false);
assert.equal(ctx.movementMatchesSnapshot({a:[1,2]},JSON.stringify({a:[2,1]})),false);
ctx.renderMovementEditForm(item,0);
ctx.movementEdit.draft = {date:'2026-08-03',qty:'4',lotNo:'DRAFT',by:'User',reconcile:true};
let form = ctx.renderMovementEditForm(reordered,0);
assert.match(form,/value="DRAFT"/);
assert.match(form,/value="4"/);
assert.doesNotMatch(form,/sm-save" disabled/);
form = ctx.renderMovementEditForm({...item,qty:25},0);
assert.match(form,/value="DRAFT"/);
assert.match(form,/sm-save" disabled/);
ctx.movementEdit.error = 'Network <failure>';
assert.match(ctx.renderMovementEditForm(item,0),/Network &lt;failure>/);
assert.equal(ctx.escapeHtml(0),'0');
ctx.ITEM_TO_SLOTS = {'"><img src=x onerror=alert(1)>':[{name:'</option><img src=x>'}]};
ctx.floorplanSearchDatalist = {};
ctx.floorplanSearchInput = {value:''};
ctx.floorplanSearchMsg = {dataset:{},hidden:true};
vm.runInContext(extract('refreshSearchDatalist'),ctx);
ctx.refreshSearchDatalist();
assert.doesNotMatch(ctx.floorplanSearchDatalist.innerHTML,/<img/);
assert.match(ctx.floorplanSearchDatalist.innerHTML,/&quot;&gt;|&quot;>/);
console.log('PASS: JSONB key ordering, genuine conflicts, draft retention, visible errors, numeric validation and HTML escaping');
let renders = 0;
Object.assign(ctx,{rebuildItemToSlots(){},refreshSearchDatalist(){},renderOverviewSlotStatus(){},
  currentZoomZone:null,renderSlotEdit(){renders++},document:{querySelector(){return null},getElementById(){return {hidden:true}}},window:{}});
vm.runInContext(extract('refreshAfterRemoteChange'),ctx);
ctx.refreshAfterRemoteChange();
assert.equal(renders,1,'Initial full sync must refresh an already-open slot panel');
ctx.refreshAfterRemoteChange('K','K-04');
assert.equal(renders,1,'Unrelated slot event must not redraw the active editor');
ctx.refreshAfterRemoteChange('F','F-18');
assert.equal(renders,2,'Matching slot event refreshes the panel');
console.log('PASS: initial full-sync and matching-slot panel refresh');
let zoomRenders = 0;
Object.assign(ctx,{currentZoomZone:'M-1',renderZoomSlots(){zoomRenders++},updateZoomView(){}});
ctx.refreshAfterRemoteChange('T-1','T1-01');
assert.equal(zoomRenders,1,'T-1 context colors must refresh while M-1 is open');
ctx.refreshAfterRemoteChange('A','A-01');
assert.equal(zoomRenders,1,'Unrelated zones must not rebuild the zoom view');
