const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderWithdrawalReport(list,context){
 const {formatDate,quantity,nameFor,jobFor,statusFor,documentCount,totalDocuments,counts,statusLabels,filtersText,durationFor,completenessFor,documentsFor,varianceFor,printedAt}=context;
 const rows=list.map((t,i)=>`<tr><td class="report-num">${i+1}</td><td><strong>${esc(t.ticket_no)}</strong><small>${documentCount(t)} ใบ · 1 งาน</small></td><td>${esc(formatDate(t.created_at))}</td><td>${esc(nameFor(t.assignee_id))}</td><td>${esc(jobFor(t.job_type_id))}</td><td>${esc(t.fg_code||'—')}<small>${esc(t.fg_name||'')}</small>${t.fg_code?`<strong>${esc(quantity(t.requested_qty))} FG</strong>`:''}</td><td>${esc(statusFor(t))}</td><td>${esc(formatDate(t.started_at))}</td><td>${esc(formatDate(t.ended_at))}</td><td>${esc(durationFor(t))}</td></tr>`).join('');
 const details=list.map((t,i)=>{
  const materials=(t.materials||[]).map((l,j)=>`<tr><td class="report-num">${j+1}</td><td><strong>${esc(l.pk_code)}</strong>${l.source==='stock'?'<span class="report-outside"> · นอก BOM</span>':''}<small>${esc(l.pk_name)}</small></td><td>${esc(l.unit)}</td><td class="report-num">${esc(quantity(l.required_qty))}</td><td class="report-num">${l.confirmed_at?esc(quantity(l.actual_qty)):'—'}</td><td>${l.confirmed_at?esc(varianceFor(l)):'ยังไม่บันทึก'}</td><td>${esc(l.short_reason||'—')}</td></tr>`).join('');
  return `<section class="report-detail"><table class="report-material-table"><colgroup><col style="width:4%"><col style="width:40%"><col style="width:7%"><col style="width:10%"><col style="width:10%"><col style="width:14%"><col style="width:15%"></colgroup><thead><tr><th colspan="7" class="report-ticket-heading"><div><strong>${i+1}. ${esc(t.ticket_no)}</strong><span>${esc(statusFor(t))} · ${documentCount(t)} ใบ</span></div><p>${esc(nameFor(t.assignee_id))} · ${esc(jobFor(t.job_type_id))}${t.fg_code?` · FG ${esc(t.fg_code)} · ${esc(quantity(t.requested_qty))} FG`:''}</p><p>${esc(t.fg_name||'')} · ${esc(completenessFor(t))}</p></th></tr><tr><th>#</th><th>รหัส / รายการบรรจุภัณฑ์</th><th>หน่วย</th><th class="report-num">ตามใบเบิก</th><th class="report-num">เบิกจริง</th><th>ผลตรวจจำนวน</th><th>เหตุผล / หมายเหตุ</th></tr></thead><tbody>${materials||'<tr><td colspan="7">ไม่มีรายการวัสดุในใบเบิกนี้</td></tr>'}</tbody></table><div class="report-ticket-notes">${documentsFor(t)}${t.description?`<p><strong>หมายเหตุ:</strong> ${esc(t.description)}</p>`:''}${t.status_reason?`<p><strong>เหตุผลสถานะ:</strong> ${esc(t.status_reason)}</p>`:''}</div></section>`;
 }).join('');
 return `<header class="report-document-head"><img src="../assets/bcl-favicon.png?v=20261002-1" alt="BCL"><div><p class="report-company">BIO-COSLAB · PK WMS</p><h1>รายงานใบเบิกบรรจุภัณฑ์</h1><p>คลังสินค้าบรรจุภัณฑ์</p></div><div class="report-issued"><strong>วันที่ออกรายงาน</strong><p>${esc(formatDate(printedAt))}</p><p>เวลาไทย (UTC+7)</p></div></header><div class="report-filter-line"><strong>ขอบเขตรายงาน:</strong> ${esc(filtersText)}</div><div class="report-summary"><div class="report-total"><span>ใบเบิกทั้งหมด</span><strong>${totalDocuments(list)} ใบ</strong><small>${list.length} งาน</small></div>${Object.entries(counts).map(([key,count])=>`<div><span>${esc(statusLabels[key])}</span><strong>${count}</strong></div>`).join('')}</div><h2 class="report-section-title">สรุปใบเบิก</h2><table class="report-table"><colgroup>${[3,13,9,11,10,20,8,9,9,8].map(n=>`<col style="width:${n}%">`).join('')}</colgroup><thead><tr><th>#</th><th>เลขที่ใบเบิก</th><th>วันที่สร้าง</th><th>พนักงาน</th><th>ประเภทงาน</th><th>FG / จำนวน</th><th>สถานะ</th><th>เริ่มงาน</th><th>สิ้นสุด</th><th>เวลาสุทธิ</th></tr></thead><tbody>${rows||'<tr><td colspan="10">ไม่พบใบเบิกตามตัวกรอง</td></tr>'}</tbody></table>${list.length?`<h2 class="report-section-title report-detail-title">รายละเอียดบรรจุภัณฑ์ตามใบเบิก</h2>${details}`:''}<footer class="report-note">ข้อมูลวัสดุและยอดเบิกจริงตามใบเบิก ไม่ใช่ยอดตัดสต็อก · เวลาสุทธิหักพักและเวลานอกกะ · เอกสารสำหรับใช้งานภายใน BIO-COSLAB</footer>`;
}
